name: Vulnerability Check

on:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 08:00 UTC
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
